source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "mongo"
gem "bson"
gem "mongoid"
gem "mongoid-pagination"
gem "redcarpet"
gem "thin"
gem "roo"
gem "rake"
gem "redis"
gem "rack-contrib"
gem "rack-attack"
gem "dotenv"
gem "geoip"
gem "rest-client"

group :development, :test do
  gem "rspec"
  gem "rack-test"
  gem "database_cleaner", github: "DatabaseCleaner/database_cleaner"
  gem "simplecov"
  gem "fabrication"
  gem "coveralls"
end