source 'https://rubygems.org'

gem 'bson'
gem 'dotenv'
gem 'geoip'
gem 'mongo'
gem 'mongoid'
gem 'mongoid-pagination'
gem 'rack-attack'
gem 'rack-contrib'
gem 'rake'
gem 'redcarpet'
gem 'redis'
gem 'rest-client'
gem 'rollbar'
gem 'roo'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'

group :development, :test do
  gem 'coveralls'
  gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner'
  gem 'fabrication'
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov'
end